import sqlite3
import os
from datetime import datetime, timezone

DB_PATH = "data/krishna_analytics.db"

def init_db():
    """
    Initializes the SQLite database and creates the necessary tables with 
    relational integrity and strict schema validation.
    
    Tables created:
    - sessions: Tracks WebSocket connection lifecycles.
    - conversations: Tracks individual AI interactions and latency metrics.
    - errors: Records system failures and diagnostic context.
    """
    os.makedirs("data", exist_ok=True)
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("PRAGMA foreign_keys = ON")
        cursor = conn.cursor()
        
        # 1. Sessions Table
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS sessions (
                session_id TEXT PRIMARY KEY NOT NULL,
                start_time DATETIME NOT NULL,
                end_time DATETIME,
                status TEXT NOT NULL
            )
        ''')
        
        # 2. Conversations Table (Updated with Total Latency)
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS conversations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id TEXT NOT NULL,
                timestamp DATETIME NOT NULL,
                user_input TEXT,
                bot_response TEXT,
                llm_latency_ms REAL,
                total_latency_ms REAL,
                FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
            )
        ''')
        
        # 3. Errors Table
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS errors (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp DATETIME NOT NULL,
                error_message TEXT NOT NULL,
                error_type TEXT,
                context TEXT
            )
        ''')

def log_conversation(session_id, user_input, bot_response, llm_latency, total_latency):
    """
    Inserts a new conversation record into the database.
    
    Args:
        session_id (str): The unique UUID for the current session.
        user_input (str): The text recognized from user speech.
        bot_response (str): The text generated by the LLM.
        llm_latency (float): Processing time for STT + LLM (ms).
        total_latency (float): Total time including TTS generation (ms).
    """
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("PRAGMA foreign_keys = ON")
        cursor = conn.cursor()
        cursor.execute('''
            INSERT INTO conversations (session_id, timestamp, user_input, bot_response, llm_latency_ms, total_latency_ms)
            VALUES (?, ?, ?, ?, ?, ?)
        ''', (session_id, datetime.now(timezone.utc), user_input, bot_response, llm_latency, total_latency))

def log_session_start(session_id):
    """
    Records the start of a new WebSocket session.
    
    Args:
        session_id (str): The unique UUID for the session.
    """
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("PRAGMA foreign_keys = ON")
        cursor = conn.cursor()
        cursor.execute('''
            INSERT OR IGNORE INTO sessions (session_id, start_time, status)
            VALUES (?, ?, ?)
        ''', (session_id, datetime.now(timezone.utc), 'active'))

def log_session_end(session_id):
    """
    Updates a session record to mark it as completed.
    
    Args:
        session_id (str): The unique UUID for the session.
    """
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("PRAGMA foreign_keys = ON")
        cursor = conn.cursor()
        cursor.execute('''
            UPDATE sessions SET end_time = ?, status = ? WHERE session_id = ?
        ''', (datetime.now(timezone.utc), 'completed', session_id))

def log_error(timestamp, error_message, error_type, context):
    """
    Logs a system error or failure for diagnostic analysis.
    
    Args:
        timestamp (datetime): The UTC timestamp of the error.
        error_message (str): A descriptive message of the failure.
        error_type (str): A category code for the error (e.g., VOICE_FAILURE).
        context (str): Additional context like session IDs or stack traces.
    """
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("PRAGMA foreign_keys = ON")
        cursor = conn.cursor()
        cursor.execute('''
            INSERT INTO errors (timestamp, error_message, error_type, context)
            VALUES (?, ?, ?, ?)
        ''', (timestamp, error_message, error_type, context))
